TABLE_USERS = "users"
USERS_COLUMN_ID = "id"
USERS_COLUMN_USERNAME = "username"
USERS_COLUMN_PASSWORD = "password"

TABLE_GROUPS = "groups"
GROUPS_COLUMN_ID = "id"
GROUPS_COLUMN_NAME = "groupname"

TABLE_USERS_FRIEND = "users_friend"
USERS_FRIEND_COLUMN_USERNAME_1 = "username_1"
USERS_FRIEND_COLUMN_USERNAME_2 = "username_2"

TABLE_GROUPS_USER = "groups_member"
GROUPS_USER_COLUMN_GROUPNAME = "groupname"
GROUPS_USER_COLUMN_USERNAME = "username"
GROUPS_USER_COLUMN_ROLE = "role"

KEY_RESPONSE_STATUS = "status"
RESPONSE_STATUS_SUCCESS = "ok"
RESPONSE_STATUS_UNKNOWN_LOGIN = "unregistered"
RESPONSE_STATUS_ERROR = "error"
RESPONSE_STATUS_WRONG_LOGIN = "wrong"
RESPONSE_STATUS_DUPLICATE = "duplicate"
RESPONSE_STATUS_FRIEND_EXISTING = "existing"

KEY_RESPONSE_USERID = "user_id"
KEY_RESPONSE_LIST_GROUPS = "groups"
KEY_RESPONSE_LIST_FRIENDS = "friends"

ROLE_USER = 0
ROLE_ADMIN = 1
